apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-llmops
  labels:
    app.kubernetes.io/name: llmops
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
