apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-human-oversight
  labels:
    app.kubernetes.io/name: human-oversight
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
