apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-billing-and-metering
  labels:
    app.kubernetes.io/name: billing-and-metering
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
