"""SDK code generation from a real OpenAPI spec (LLD §Level 1 "SDK
source"). Pure, deterministic, no I/O -- the same input spec always
produces the same output source, which is exactly what makes
`SdkGeneratorService`'s spec-hash-keyed idempotency correct. Like
`EnvelopeCipher` (Secrets and Credential Management, Module 32) and
`two_proportion_z_test` (PromptOps, Module 29), pure functions like
these need no fake for unit tests -- tests call the real thing
directly.
"""
from __future__ import annotations

import re
from typing import Any

_HTTP_METHODS = ("get", "post", "put", "patch", "delete")


def _class_name(module_name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[-_]", module_name) if part) + "Client"


def _slug(path: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", path).strip("_")


def _pythonize(identifier: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9]+", "_", identifier).strip("_").lower()
    if not name:
        name = "call"
    if name[0].isdigit():
        name = f"_{name}"
    return name


def generate_python_client(*, module_name: str, base_url: str, spec: dict[str, Any]) -> str:
    """Turns an OpenAPI spec's `paths` into a minimal, real, working
    `httpx`-based client class -- one method per (path, HTTP verb),
    named from the spec's own `operationId` when present."""
    class_name = _class_name(module_name)
    info = spec.get("info", {})
    title = info.get("title", module_name)

    lines = [
        f'"""Auto-generated by SDK and Developer Portal (Module 34) from {module_name}\'s',
        f'real, live OpenAPI spec ({title}). Do not edit by hand -- regenerate instead."""',
        "from __future__ import annotations",
        "",
        "import httpx",
        "",
        "",
        f"class {class_name}:",
        f'    """Minimal client for {module_name} ({base_url})."""',
        "",
        "    def __init__(self, base_url: str, token: str) -> None:",
        '        self._client = httpx.Client(base_url=base_url, headers={"Authorization": f"Bearer {token}"})',
        "",
    ]

    paths: dict[str, Any] = spec.get("paths", {})
    used_names: set[str] = set()
    for path in sorted(paths):
        operations = paths[path]
        for method in sorted(operations):
            if method.lower() not in _HTTP_METHODS:
                continue
            operation = operations[method]
            operation_id = operation.get("operationId") or f"{method}_{_slug(path)}"
            method_name = _pythonize(operation_id)
            # operationIds can collide across paths in a loosely-specced peer; a numeric
            # suffix keeps every generated method callable rather than silently
            # overwriting an earlier one.
            base_name = method_name
            suffix = 2
            while method_name in used_names:
                method_name = f"{base_name}_{suffix}"
                suffix += 1
            used_names.add(method_name)

            lines.append(f"    def {method_name}(self, **kwargs) -> httpx.Response:")
            lines.append(f"        return self._client.{method.lower()}({path!r}, **kwargs)")
            lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"
