apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agentic-rag
  labels:
    app.kubernetes.io/name: agentic-rag
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
