apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-evaluation-framework
  labels:
    app.kubernetes.io/name: evaluation-framework
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
