apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-guardrails
  labels:
    app.kubernetes.io/name: guardrails
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
