apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-multi-tenancy
  labels:
    app.kubernetes.io/name: multi-tenancy
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
