apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agent-cards
  labels:
    app.kubernetes.io/name: agent-cards
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
