apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-regulatory-compliance
  labels:
    app.kubernetes.io/name: regulatory-compliance
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
