apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-tool-orchestration
  labels:
    app.kubernetes.io/name: tool-orchestration
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
