apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-promptops
  labels:
    app.kubernetes.io/name: promptops
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
