apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-graph-db
  labels:
    app.kubernetes.io/name: graph-db
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
