apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-secrets-and-credential-management
  labels:
    app.kubernetes.io/name: secrets-and-credential-management
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
