apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-short-term-memory
  labels:
    app.kubernetes.io/name: short-term-memory
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
