apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sentinel-agents
  labels:
    app.kubernetes.io/name: sentinel-agents
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
