apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-intent-detection
  labels:
    app.kubernetes.io/name: intent-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
