apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-data-source-plugins
  labels:
    app.kubernetes.io/name: data-source-plugins
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
