apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-identity-and-access
  labels:
    app.kubernetes.io/name: identity-and-access
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
