apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-knowledge-base
  labels:
    app.kubernetes.io/name: knowledge-base
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
