apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-multi-modality
  labels:
    app.kubernetes.io/name: multi-modality
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
