apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-a2a
  labels:
    app.kubernetes.io/name: a2a
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
