apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-sdk-and-developer-portal
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sdk-and-developer-portal
      app.kubernetes.io/instance: {{ .Release.Name }}
