apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sdk-and-developer-portal
  labels:
    app.kubernetes.io/name: sdk-and-developer-portal
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
