apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-deployment-strategy
  labels:
    app.kubernetes.io/name: deployment-strategy
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
