apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-workflow-engine
  labels:
    app.kubernetes.io/name: workflow-engine
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
